/**
 * Syncs:
 * (a) AGENTS.md autogen block from .agents/rules/*.md (lexicographic)
 * (b) .cursor/rules/*.mdc from agents-manifest.yaml
 * (c) .continue/rules/*.md from agents-manifest.yaml
 *
 * Usage: npx tsx scripts/sync-agents.ts [--check]
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const CHECK = process.argv.includes("--check");

const BEGIN = "<!-- BEGIN AUTOGEN -->";
const END = "<!-- END AUTOGEN -->";

type CursorRule = {
  output: string;
  source: string;
  description: string;
  globs?: string[];
  alwaysApply?: boolean;
};

type ContinueRule = {
  output: string;
  source: string;
};

type Manifest = {
  cursorRules: CursorRule[];
  continueRules: ContinueRule[];
};

function readText(path: string): string {
  return readFileSync(path, "utf8");
}

function writeText(path: string, content: string): void {
  if (!CHECK) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf8");
  }
}

function ensureEqual(path: string, next: string, label: string): void {
  if (!existsSync(path)) {
    if (CHECK) {
      console.error(`[check] missing ${label}: ${relative(ROOT, path)}`);
      process.exit(1);
    }
    writeText(path, next);
    return;
  }
  const cur = readText(path);
  if (cur !== next) {
    console.error(`[check] drift in ${label}: ${relative(ROOT, path)}`);
    process.exit(1);
  }
}

function buildAutogenBody(): string {
  const dir = join(ROOT, ".agents", "rules");
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort((a, b) => a.localeCompare(b));
  const parts: string[] = [];
  for (const f of files) {
    parts.push(readText(join(dir, f)).trimEnd());
  }
  return ["## Autogenerated modular rules", "", parts.join("\n\n"), ""].join("\n");
}

function patchAgents(autogen: string): string {
  const agentsPath = join(ROOT, "AGENTS.md");
  const src = readText(agentsPath);
  const i0 = src.indexOf(BEGIN);
  const i1 = src.indexOf(END);
  if (i0 === -1 || i1 === -1 || i1 <= i0) {
    throw new Error("AGENTS.md must contain AUTOGEN markers");
  }
  const before = src.slice(0, i0 + BEGIN.length);
  const after = src.slice(i1);
  return `${before}\n\n${autogen.trimEnd()}\n\n${after}`;
}

function yamlStringList(values: string[]): string {
  return values.map((g) => `  - ${JSON.stringify(g)}`).join("\n");
}

function buildCursorMdc(rule: CursorRule): string {
  const body = readText(join(ROOT, rule.source)).trimEnd();
  const globs =
    rule.globs && rule.globs.length
      ? `\nglobs:\n${yamlStringList(rule.globs)}\n`
      : "\n";
  const always = `alwaysApply: ${rule.alwaysApply === true ? "true" : "false"}\n`;
  const fm = `---\ndescription: ${JSON.stringify(rule.description)}${globs}${always}---\n\n`;
  return `${fm}${body}\n`;
}

function syncCursor(manifest: Manifest): void {
  for (const rule of manifest.cursorRules) {
    const out = join(ROOT, ".cursor", "rules", rule.output);
    const next = buildCursorMdc(rule);
    if (CHECK) {
      ensureEqual(out, next, "cursor rule");
    } else {
      writeText(out, next);
    }
  }
}

function syncContinue(manifest: Manifest): void {
  for (const rule of manifest.continueRules) {
    const out = join(ROOT, ".continue", "rules", rule.output);
    const next = `${readText(join(ROOT, rule.source)).trimEnd()}\n`;
    if (CHECK) {
      ensureEqual(out, next, "continue rule");
    } else {
      writeText(out, next);
    }
  }
}

function main(): void {
  const manifestPath = join(ROOT, "agents-manifest.yaml");
  const manifest = parse(readText(manifestPath)) as Manifest;
  const autogen = buildAutogenBody();
  const agentsPath = join(ROOT, "AGENTS.md");
  const nextAgents = patchAgents(autogen);

  if (CHECK) {
    ensureEqual(agentsPath, nextAgents, "AGENTS.md");
  } else {
    writeFileSync(agentsPath, nextAgents, "utf8");
  }

  syncCursor(manifest);
  syncContinue(manifest);

  if (CHECK) {
    console.log("sync-agents: OK (no drift)");
  } else {
    console.log("sync-agents: wrote AGENTS.md, .cursor/rules, .continue/rules");
  }
}

main();
